### ISSUE TITLE
fix volume on main page

### ISSUE THREAD

**Issue by nb110240** [cse110-sp23-group10/cse110-sp23-group10#42]
when you land on the main page the volume does not work immediately unless we go to the fortune page - or go to the fortune page and come back to the main page.

**Comment by kjchou324** [comment]
I was looking this up and found this

https://developer.chrome.com/blog/autoplay/

Maybe we should have it prompt the user to play the audio if they want when they click the mute button for the first time, and have the audio start as muted/disabled on load.

**Comment by mohakvni** [comment]
Done!
